# This is a workflow to build and deploy the rust project to Github Pages 
# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ main ]

jobs:
  check:
    name: first book project
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: cargo install mdbook
        - name: Install mdbook-quiz
          run: cargo install --path . --debug --locked
        - name: Build example mdbook
          run: mdbook build
#           working-directory: example
#         - run: mdbook build
        - name: first-book project
          if: success()
          uses: crazy-max/ghaction-github-pages@v2
          with:
            target_branch: main
            build_dir: book
            keep_history: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

